version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - "8080:8080"
    tty: true
    # volumes:
    #   - ./api:/app

  next:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./next:/usr/src/app 
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"